### ISSUE TITLE
wrong name in pubspec.yaml

### ISSUE THREAD

**Issue by keep-on-learning** [pelodart/dart_shapes#1]
@pelodart in pubspec.yaml 'name: time' in 'name: shapes' ändern
<img width="503" alt="Bildschirmfoto 2019-05-08 um 16 37 21" src="https://user-images.githubusercontent.com/49608551/57383719-92f11780-71af-11e9-9370-f720e5d08e86.png">

**Comment by pelodart** [comment]
Done.
